import type { Course } from "@/types";

/**
 * 大学のシラバスサイト (cx.asahikawa-u.ac.jp) へ未接続の状態でもアプリが
 * 完全に動作するためのデモ科目データ（経済学部経営経済学科を想定）。
 * 必修科目名は参考実装(旭川時間割アドバイザー)のrequiredCourseNamesに合わせてあり、
 * 選択必修A〜Eは科目名から自動分類される（categoryKeyを付けていない科目は
 * src/lib/graduation-requirements.ts の classifyCourse() が自動判定する）。
 * 実データはVer.2のスクレイパー(src/lib/scraper.ts)が初めて検索された時に取得し、
 * IndexedDBへキャッシュされたものに置き換わっていく。
 */
const now = Date.now();

function course(partial: Omit<Course, "source" | "cachedAt" | "keywords" | "department" | "faculty"> & { keywords?: string[] }): Course {
  return {
    source: "demo",
    cachedAt: now,
    keywords: partial.keywords ?? [],
    faculty: "経済学部",
    department: "経営経済学科",
    ...partial,
  };
}

export const DEMO_COURSES: Course[] = [
  // ---- 必修（参考実装のrequiredCourseNamesと一致させ、自動判定を確認できるようにしてある） ----
  course({
    id: "demo-req-01",
    name: "経済学(経済)",
    teacher: "佐藤 一郎",
    credits: 4,
    targetYears: [1],
    semester: "通年",
    day: "月",
    period: 1,
    room: "301",
    overview: "経済学全般の基礎概念を学ぶ導入科目。需要と供給、市場、GDP、経済政策の基本的な考え方を扱う。",
    evaluation: [{ type: "試験", percentage: 80 }, { type: "出席", percentage: 20 }],
    keywords: ["経済学", "入門"],
    categoryKey: "必修",
  }),
  course({
    id: "demo-req-02",
    name: "理論経済学入門",
    teacher: "佐藤 一郎",
    credits: 2,
    targetYears: [1],
    semester: "前期",
    day: "月",
    period: 3,
    room: "301",
    overview: "ミクロ・マクロ経済学の理論的基礎を数式を用いずに概観する。",
    evaluation: [{ type: "試験", percentage: 100 }],
    keywords: ["理論経済学"],
    categoryKey: "必修",
  }),
  course({
    id: "demo-req-03",
    name: "経営学Ⅰ",
    teacher: "伊藤 剛",
    credits: 2,
    targetYears: [1],
    semester: "前期",
    day: "火",
    period: 1,
    room: "305",
    overview: "企業経営の基本概念、組織論の入門的内容を学ぶ。",
    evaluation: [{ type: "レポート", percentage: 50 }, { type: "出席", percentage: 50 }],
    keywords: ["経営学"],
    categoryKey: "必修",
  }),
  course({
    id: "demo-req-04",
    name: "経営学Ⅱ",
    teacher: "伊藤 剛",
    credits: 2,
    targetYears: [1],
    semester: "後期",
    day: "火",
    period: 1,
    room: "305",
    overview: "経営学Ⅰに続き、戦略論・マーケティングの基礎を学ぶ。",
    evaluation: [{ type: "レポート", percentage: 50 }, { type: "出席", percentage: 50 }],
    keywords: ["経営学", "戦略論"],
    categoryKey: "必修",
  }),
  course({
    id: "demo-req-05",
    name: "簿記原理Ⅰ",
    teacher: "渡辺 学",
    credits: 2,
    targetYears: [1],
    semester: "前期",
    day: "火",
    period: 2,
    room: "306",
    overview: "複式簿記の基本原理と仕訳・決算処理を実習形式で習得する。",
    evaluation: [{ type: "試験", percentage: 80 }, { type: "小テスト", percentage: 20 }],
    keywords: ["簿記"],
    categoryKey: "必修",
  }),
  course({
    id: "demo-req-06",
    name: "簿記原理Ⅱ",
    teacher: "渡辺 学",
    credits: 2,
    targetYears: [1],
    semester: "後期",
    day: "火",
    period: 2,
    room: "306",
    overview: "簿記原理Ⅰに続き、株式会社会計・決算整理を学ぶ。",
    evaluation: [{ type: "試験", percentage: 80 }, { type: "小テスト", percentage: 20 }],
    keywords: ["簿記"],
    categoryKey: "必修",
  }),
  course({
    id: "demo-req-07",
    name: "会計学Ⅰ",
    teacher: "中村 学",
    credits: 2,
    targetYears: [1, 2],
    semester: "前期",
    day: "水",
    period: 1,
    room: "302",
    overview: "財務会計の基礎理論、貸借対照表・損益計算書の構造を学ぶ。",
    evaluation: [{ type: "試験", percentage: 100 }],
    keywords: ["会計"],
    categoryKey: "必修",
  }),
  course({
    id: "demo-req-08",
    name: "会計学Ⅱ",
    teacher: "中村 学",
    credits: 2,
    targetYears: [1, 2],
    semester: "後期",
    day: "水",
    period: 1,
    room: "302",
    overview: "会計学Ⅰに続き、キャッシュフロー計算書・連結会計の基礎を学ぶ。",
    evaluation: [{ type: "試験", percentage: 100 }],
    keywords: ["会計"],
    categoryKey: "必修",
  }),
  course({
    id: "demo-req-09",
    name: "情報処理Ⅰa",
    teacher: "木村 学",
    credits: 1,
    targetYears: [1],
    semester: "前期",
    day: "水",
    period: 2,
    room: "PC教室2",
    overview: "表計算ソフトの基本操作とデータ処理の基礎を演習形式で学ぶ。",
    evaluation: [{ type: "小テスト", percentage: 50 }, { type: "出席", percentage: 50 }],
    keywords: ["情報処理", "Excel"],
    categoryKey: "必修",
  }),
  course({
    id: "demo-req-10",
    name: "情報処理Ⅰb",
    teacher: "木村 学",
    credits: 1,
    targetYears: [1],
    semester: "後期",
    day: "水",
    period: 2,
    room: "PC教室2",
    overview: "情報処理Ⅰaに続き、プレゼンテーション資料作成とデータ分析の基礎を学ぶ。",
    evaluation: [{ type: "小テスト", percentage: 50 }, { type: "出席", percentage: 50 }],
    keywords: ["情報処理", "プレゼンテーション"],
    categoryKey: "必修",
  }),
  course({
    id: "demo-req-11",
    name: "キャリア形成論",
    teacher: "井上 恵子",
    credits: 2,
    targetYears: [1, 2],
    semester: "前期",
    day: "金",
    period: 1,
    room: "301",
    overview: "自己分析、業界研究、キャリアデザインの基礎を学び、進路選択への意識を高める。",
    evaluation: [{ type: "レポート", percentage: 60 }, { type: "出席", percentage: 40 }],
    keywords: ["キャリア", "進路"],
    categoryKey: "必修",
  }),
  course({
    id: "demo-req-12",
    name: "ゼミナールI",
    teacher: "佐藤 一郎",
    credits: 4,
    targetYears: [3],
    semester: "通年",
    day: "金",
    period: 3,
    room: "ゼミ室1",
    overview: "少人数制で経済学のテーマを選び、文献講読と研究発表を行う。",
    evaluation: [{ type: "平常点", percentage: 60 }, { type: "レポート", percentage: 40 }],
    keywords: ["ゼミ", "演習", "卒業論文"],
    categoryKey: "必修", // 参考実装のリストには無いが、多くのカリキュラムで必修指定されるため手動指定
  }),

  // ---- 選択必修A: マクロ|ミクロ|理論|経済学史 等（科目名から自動分類） ----
  course({
    id: "demo-001",
    name: "ミクロ経済学",
    nameKana: "みくろけいざいがく",
    teacher: "佐藤 一郎",
    credits: 2,
    targetYears: [1, 2],
    semester: "前期",
    day: "月",
    period: 2,
    room: "301",
    overview: "消費者・企業の意思決定と市場均衡の基礎理論を学ぶ。需要と供給、弾力性、市場の失敗などを扱う。",
    evaluation: [
      { type: "試験", percentage: 60 },
      { type: "小テスト", percentage: 20 },
      { type: "出席", percentage: 20 },
    ],
    textbook: "『ミクロ経済学の基礎』",
    keywords: ["ミクロ", "需要", "供給", "市場均衡"],
  }),
  course({
    id: "demo-002",
    name: "マクロ経済学",
    nameKana: "まくろけいざいがく",
    teacher: "鈴木 花子",
    credits: 2,
    targetYears: [1, 2],
    semester: "後期",
    day: "月",
    period: 2,
    room: "301",
    overview: "GDP、物価、失業、金融政策・財政政策など一国経済全体の動きを分析する。",
    evaluation: [
      { type: "試験", percentage: 70 },
      { type: "レポート", percentage: 30 },
    ],
    keywords: ["マクロ", "GDP", "金融政策", "財政政策"],
  }),
  course({
    id: "demo-013",
    name: "経済学史",
    teacher: "松本 誠",
    credits: 2,
    targetYears: [2, 3],
    semester: "後期",
    day: "金",
    period: 1,
    room: "305",
    overview: "アダム・スミスからケインズ、現代までの経済学説の展開を概観する。",
    evaluation: [{ type: "試験", percentage: 100 }],
    keywords: ["経済学史", "経済思想"],
  }),

  // ---- 選択必修B: 国際|地域|北海道|農業|労働|政策|社会保障|経済地理 ----
  course({
    id: "demo-007",
    name: "国際経済学",
    teacher: "山本 恵子",
    credits: 2,
    targetYears: [2, 3],
    semester: "後期",
    day: "火",
    period: 3,
    room: "301",
    overview: "貿易理論、為替レート、国際収支など国際経済の基礎理論と現実の国際経済問題を扱う。",
    evaluation: [{ type: "試験", percentage: 60 }, { type: "レポート", percentage: 40 }],
    keywords: ["貿易", "為替", "国際収支"],
  }),
  course({
    id: "demo-008",
    name: "労働経済学",
    teacher: "小林 誠",
    credits: 2,
    targetYears: [2, 3],
    semester: "前期",
    day: "水",
    period: 3,
    room: "302",
    overview: "労働市場の需給、賃金決定メカニズム、雇用政策について経済学の視点から分析する。",
    evaluation: [{ type: "試験", percentage: 100 }],
    keywords: ["労働市場", "賃金", "雇用"],
  }),
  course({
    id: "demo-012",
    name: "地域経済論",
    teacher: "斎藤 学",
    credits: 2,
    targetYears: [3, 4],
    semester: "前期",
    day: "木",
    period: 3,
    room: "304",
    overview: "旭川・北海道を事例に、地域経済の構造と地域振興政策について学ぶ。",
    evaluation: [{ type: "レポート", percentage: 100 }],
    keywords: ["地域経済", "地域振興", "北海道"],
  }),

  // ---- 選択必修C: 経営|企業|組織|人的資源|キャリア ----
  course({
    id: "demo-005",
    name: "経営学入門",
    teacher: "伊藤 剛",
    credits: 2,
    targetYears: [1, 2],
    semester: "前期",
    day: "木",
    period: 1,
    room: "305",
    overview: "経営学Ⅰ・Ⅱの発展として、企業経営の実践事例を交えながら組織論・戦略論を学ぶ。",
    evaluation: [
      { type: "レポート", percentage: 50 },
      { type: "出席", percentage: 50 },
    ],
    keywords: ["経営", "組織論", "戦略"],
  }),
  course({
    id: "demo-020",
    name: "マーケティング論",
    teacher: "山田 恵",
    credits: 2,
    targetYears: [2, 3],
    semester: "前期",
    day: "木",
    period: 2,
    room: "303",
    overview: "市場調査、製品戦略、価格戦略、プロモーション戦略などマーケティングの基礎理論を学ぶ。",
    evaluation: [{ type: "試験", percentage: 40 }, { type: "レポート", percentage: 40 }, { type: "出席", percentage: 20 }],
    keywords: ["マーケティング", "市場調査"],
  }),

  // ---- 選択必修D: 会計|簿記|財務|原価|商品|マーチャン ----
  course({
    id: "demo-006",
    name: "簿記論",
    teacher: "渡辺 学",
    credits: 2,
    targetYears: [2, 3],
    semester: "前期",
    day: "木",
    period: 4,
    room: "306",
    overview: "簿記原理Ⅰ・Ⅱを発展させ、日商簿記検定2級レベルの応用論点を扱う。",
    evaluation: [{ type: "試験", percentage: 80 }, { type: "小テスト", percentage: 20 }],
    keywords: ["簿記", "会計", "仕訳"],
  }),
  course({
    id: "demo-023",
    name: "財務諸表論",
    teacher: "中村 学",
    credits: 2,
    targetYears: [2, 3],
    semester: "後期",
    day: "木",
    period: 4,
    room: "302",
    overview: "財務諸表の作成・分析手法を学び、企業の経営状態を読み解く力を養う。",
    evaluation: [{ type: "試験", percentage: 100 }],
    keywords: ["財務諸表", "経営分析"],
  }),

  // ---- 選択必修E: 法|憲法|民法|行政法|情報|数学|地理|地誌|倫理|異文化|総合 ----
  course({
    id: "demo-004",
    name: "経済数学",
    teacher: "田中 修",
    credits: 2,
    targetYears: [1],
    semester: "前期",
    day: "月",
    period: 4,
    room: "203",
    overview: "経済分析に必要な微分・積分・線形代数の基礎を、経済モデルへの応用とともに学ぶ。",
    evaluation: [{ type: "試験", percentage: 100 }],
    keywords: ["数学", "微分", "線形代数"],
  }),
  course({
    id: "demo-017",
    name: "情報処理演習",
    teacher: "木村 学",
    credits: 1,
    targetYears: [2],
    semester: "前期",
    day: "金",
    period: 2,
    room: "PC教室1",
    overview: "情報処理Ⅰa/Ⅰbの発展として、データベース・統計ソフトの活用法を演習形式で学ぶ。",
    evaluation: [{ type: "小テスト", percentage: 50 }, { type: "出席", percentage: 50 }],
    keywords: ["情報処理", "データベース", "情報リテラシー"],
  }),
  course({
    id: "demo-016",
    name: "民法概論",
    teacher: "Smith John",
    credits: 2,
    targetYears: [1, 2],
    semester: "前期",
    day: "火",
    period: 4,
    room: "401",
    overview: "契約・不法行為など、経済活動に関わる民法の基礎を学ぶ。",
    evaluation: [{ type: "出席", percentage: 40 }, { type: "小テスト", percentage: 30 }, { type: "レポート", percentage: 30 }],
    keywords: ["法学", "民法", "契約"],
  }),

  // ---- 選択（自動分類でどの区分にも一致しない科目） ----
  course({
    id: "demo-003",
    name: "統計学",
    teacher: "高橋 誠",
    credits: 2,
    targetYears: [1, 2],
    semester: "前期",
    day: "月",
    period: 5,
    room: "202",
    overview: "記述統計・確率分布・推測統計の基礎を演習を交えて学ぶ。経済データ分析への応用も扱う。",
    evaluation: [
      { type: "試験", percentage: 50 },
      { type: "レポート", percentage: 30 },
      { type: "出席", percentage: 20 },
    ],
    keywords: ["統計", "確率", "回帰分析"],
  }),
  course({
    id: "demo-009",
    name: "財政学",
    teacher: "中村 学",
    credits: 2,
    targetYears: [2, 3],
    semester: "後期",
    day: "水",
    period: 4,
    room: "302",
    overview: "政府の財政活動、租税制度、公共財の理論、財政政策の効果について学ぶ。",
    evaluation: [{ type: "試験", percentage: 70 }, { type: "出席", percentage: 30 }],
    keywords: ["財政", "租税", "公共財"],
  }),
  course({
    id: "demo-010",
    name: "金融論",
    teacher: "加藤 修",
    credits: 2,
    targetYears: [2, 3],
    semester: "前期",
    day: "水",
    period: 5,
    room: "303",
    overview: "銀行・金融市場の仕組み、金融政策の波及経路、金融危機の要因などを学ぶ。",
    evaluation: [{ type: "試験", percentage: 60 }, { type: "レポート", percentage: 40 }],
    keywords: ["金融", "銀行", "金融政策"],
  }),
  course({
    id: "demo-011",
    name: "計量経済学",
    teacher: "吉田 誠",
    credits: 2,
    targetYears: [2, 3],
    semester: "後期",
    day: "木",
    period: 5,
    room: "PC教室1",
    overview: "回帰分析を中心とした計量経済学の基礎理論と統計ソフトを用いた実証分析の演習を行う。",
    evaluation: [{ type: "レポート", percentage: 60 }, { type: "出席", percentage: 40 }],
    keywords: ["計量経済学", "回帰分析", "実証分析"],
  }),
  course({
    id: "demo-014",
    name: "経済政策論",
    teacher: "井上 恵子",
    credits: 2,
    targetYears: [3, 4],
    semester: "前期",
    day: "金",
    period: 4,
    room: "301",
    overview: "現代日本の経済政策（金融・財政・産業政策等）を理論と実際の両面から検討する。",
    evaluation: [{ type: "試験", percentage: 50 }, { type: "レポート", percentage: 50 }],
    keywords: ["経済政策", "産業政策"],
  }),
  course({
    id: "demo-021",
    name: "産業組織論",
    teacher: "西田 誠",
    credits: 2,
    targetYears: [3, 4],
    semester: "後期",
    day: "水",
    period: 6,
    room: "306",
    overview: "企業行動・市場構造・競争政策をゲーム理論等のミクロ経済学の手法を用いて分析する。",
    evaluation: [{ type: "試験", percentage: 80 }, { type: "出席", percentage: 20 }],
    keywords: ["産業組織", "ゲーム理論", "競争政策"],
    offeredYears: [2027],
  }),

  // ---- 自由選択（一般教養科目。regexパターンに一致しないため手動指定） ----
  course({
    id: "demo-018",
    name: "哲学",
    teacher: "森田 修",
    credits: 2,
    targetYears: [1, 2],
    semester: "後期",
    day: "木",
    period: 6,
    room: "202",
    overview: "西洋哲学の主要な思想潮流を概観し、現代社会の諸問題を哲学的に考察する。",
    evaluation: [{ type: "レポート", percentage: 100 }],
    keywords: ["哲学", "思想"],
    categoryKey: "自由選択",
  }),
  course({
    id: "demo-019",
    name: "スポーツ実技",
    teacher: "体育 太郎",
    credits: 1,
    targetYears: [1, 2],
    semester: "前期",
    day: "金",
    period: 5,
    room: "体育館",
    overview: "生涯スポーツの視点から、実技を通じて健康・体力づくりの意義を学ぶ。",
    evaluation: [{ type: "出席", percentage: 70 }, { type: "平常点", percentage: 30 }],
    keywords: ["スポーツ", "体育"],
    categoryKey: "自由選択",
  }),
  course({
    id: "demo-022",
    name: "環境経済学",
    teacher: "青木 恵子",
    credits: 2,
    targetYears: [3, 4],
    semester: "前期",
    day: "火",
    period: 5,
    room: "304",
    overview: "環境問題を経済学の視点から分析し、環境政策の設計・評価手法を学ぶ。",
    evaluation: [{ type: "レポート", percentage: 70 }, { type: "出席", percentage: 30 }],
    keywords: ["環境経済学", "環境政策", "持続可能性"],
    categoryKey: "自由選択",
  }),
];

export function nextCourseId(): string {
  return `demo-${Math.random().toString(36).slice(2, 10)}`;
}
