import type { Course } from "@/types";

/**
 * 大学のシラバスサイト (cx.asahikawa-u.ac.jp) へ未接続の状態でもアプリが
 * 完全に動作するためのデモ科目データ（経済学部経済学科を想定）。
 * 実データはVer.2のスクレイパー(src/lib/scraper.ts)が初回検索時に取得し、
 * IndexedDBへキャッシュされたものに置き換わる。
 */
const now = Date.now();

function course(partial: Omit<Course, "source" | "cachedAt" | "keywords"> & { keywords?: string[] }): Course {
  return {
    source: "demo",
    cachedAt: now,
    keywords: partial.keywords ?? [],
    ...partial,
  };
}

export const DEMO_COURSES: Course[] = [
  course({
    id: "demo-001",
    name: "ミクロ経済学",
    nameKana: "みくろけいざいがく",
    teacher: "佐藤 一郎",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [1, 2],
    semester: "前期",
    day: "月",
    period: 2,
    room: "301",
    overview: "消費者・企業の意思決定と市場均衡の基礎理論を学ぶ。需要と供給、弾力性、市場の失敗などを扱う。",
    evaluation: [
      { type: "試験", percentage: 60 },
      { type: "小テスト", percentage: 20 },
      { type: "出席", percentage: 20 },
    ],
    textbook: "『ミクロ経済学の基礎』",
    keywords: ["ミクロ", "需要", "供給", "市場均衡"],
    categoryKey: "必修",
  }),
  course({
    id: "demo-002",
    name: "マクロ経済学",
    nameKana: "まくろけいざいがく",
    teacher: "鈴木 花子",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [1, 2],
    semester: "後期",
    day: "月",
    period: 2,
    room: "301",
    overview: "GDP、物価、失業、金融政策・財政政策など一国経済全体の動きを分析する。",
    evaluation: [
      { type: "試験", percentage: 70 },
      { type: "レポート", percentage: 30 },
    ],
    keywords: ["マクロ", "GDP", "金融政策", "財政政策"],
    categoryKey: "必修",
  }),
  course({
    id: "demo-003",
    name: "統計学",
    teacher: "高橋 誠",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [1, 2],
    semester: "前期",
    day: "月",
    period: 2,
    room: "202",
    overview: "記述統計・確率分布・推測統計の基礎を演習を交えて学ぶ。経済データ分析への応用も扱う。",
    evaluation: [
      { type: "試験", percentage: 50 },
      { type: "レポート", percentage: 30 },
      { type: "出席", percentage: 20 },
    ],
    keywords: ["統計", "確率", "回帰分析"],
    categoryKey: "選択必修",
    categoryGroup: "専門選択必修",
  }),
  course({
    id: "demo-004",
    name: "経済数学",
    teacher: "田中 修",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [1],
    semester: "前期",
    day: "月",
    period: 2,
    room: "203",
    overview: "経済分析に必要な微分・積分・線形代数の基礎を、経済モデルへの応用とともに学ぶ。",
    evaluation: [{ type: "試験", percentage: 100 }],
    keywords: ["数学", "微分", "線形代数"],
    categoryKey: "選択必修",
    categoryGroup: "専門選択必修",
  }),
  course({
    id: "demo-005",
    name: "経営学入門",
    teacher: "伊藤 剛",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [1, 2],
    semester: "前期",
    day: "火",
    period: 1,
    room: "305",
    overview: "企業経営の基本概念、組織論・戦略論の入門的内容を学ぶ。",
    evaluation: [
      { type: "レポート", percentage: 50 },
      { type: "出席", percentage: 50 },
    ],
    keywords: ["経営", "組織論", "戦略"],
    categoryKey: "選択",
  }),
  course({
    id: "demo-006",
    name: "簿記論",
    teacher: "渡辺 学",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [1, 2],
    semester: "前期",
    day: "火",
    period: 2,
    room: "306",
    overview: "複式簿記の基本原理と仕訳・決算処理を実習形式で習得する。日商簿記検定にも対応。",
    evaluation: [{ type: "試験", percentage: 80 }, { type: "小テスト", percentage: 20 }],
    keywords: ["簿記", "会計", "仕訳"],
    categoryKey: "選択",
  }),
  course({
    id: "demo-007",
    name: "国際経済学",
    teacher: "山本 恵子",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [2, 3],
    semester: "後期",
    day: "火",
    period: 3,
    room: "301",
    overview: "貿易理論、為替レート、国際収支など国際経済の基礎理論と現実の国際経済問題を扱う。",
    evaluation: [{ type: "試験", percentage: 60 }, { type: "レポート", percentage: 40 }],
    keywords: ["貿易", "為替", "国際収支"],
    categoryKey: "選択必修",
    categoryGroup: "専門選択必修",
  }),
  course({
    id: "demo-008",
    name: "労働経済学",
    teacher: "小林 誠",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [2, 3],
    semester: "前期",
    day: "水",
    period: 1,
    room: "302",
    overview: "労働市場の需給、賃金決定メカニズム、雇用政策について経済学の視点から分析する。",
    evaluation: [{ type: "試験", percentage: 100 }],
    keywords: ["労働市場", "賃金", "雇用"],
    categoryKey: "選択",
  }),
  course({
    id: "demo-009",
    name: "財政学",
    teacher: "中村 学",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [2, 3],
    semester: "後期",
    day: "水",
    period: 2,
    room: "302",
    overview: "政府の財政活動、租税制度、公共財の理論、財政政策の効果について学ぶ。",
    evaluation: [{ type: "試験", percentage: 70 }, { type: "出席", percentage: 30 }],
    keywords: ["財政", "租税", "公共財"],
    categoryKey: "選択必修",
    categoryGroup: "専門選択必修",
  }),
  course({
    id: "demo-010",
    name: "金融論",
    teacher: "加藤 修",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [2, 3],
    semester: "前期",
    day: "水",
    period: 3,
    room: "303",
    overview: "銀行・金融市場の仕組み、金融政策の波及経路、金融危機の要因などを学ぶ。",
    evaluation: [{ type: "試験", percentage: 60 }, { type: "レポート", percentage: 40 }],
    keywords: ["金融", "銀行", "金融政策"],
    categoryKey: "選択",
  }),
  course({
    id: "demo-011",
    name: "計量経済学",
    teacher: "吉田 誠",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [2, 3],
    semester: "後期",
    day: "木",
    period: 2,
    room: "PC教室1",
    overview: "回帰分析を中心とした計量経済学の基礎理論と統計ソフトを用いた実証分析の演習を行う。",
    evaluation: [{ type: "レポート", percentage: 60 }, { type: "出席", percentage: 40 }],
    keywords: ["計量経済学", "回帰分析", "実証分析"],
    categoryKey: "選択必修",
    categoryGroup: "専門選択必修",
  }),
  course({
    id: "demo-012",
    name: "地域経済論",
    teacher: "斎藤 学",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [3, 4],
    semester: "前期",
    day: "木",
    period: 3,
    room: "304",
    overview: "旭川・北海道を事例に、地域経済の構造と地域振興政策について学ぶ。",
    evaluation: [{ type: "レポート", percentage: 100 }],
    keywords: ["地域経済", "地域振興", "北海道"],
    categoryKey: "自由選択",
  }),
  course({
    id: "demo-013",
    name: "経済史",
    teacher: "松本 誠",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [1, 2],
    semester: "後期",
    day: "金",
    period: 1,
    room: "305",
    overview: "近現代の日本経済・世界経済の歴史的展開を概観し、現在の経済構造への理解を深める。",
    evaluation: [{ type: "試験", percentage: 100 }],
    keywords: ["経済史", "日本経済", "世界経済"],
    categoryKey: "選択",
  }),
  course({
    id: "demo-014",
    name: "経済政策論",
    teacher: "井上 恵子",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [3, 4],
    semester: "前期",
    day: "金",
    period: 2,
    room: "301",
    overview: "現代日本の経済政策（金融・財政・産業政策等）を理論と実際の両面から検討する。",
    evaluation: [{ type: "試験", percentage: 50 }, { type: "レポート", percentage: 50 }],
    keywords: ["経済政策", "産業政策"],
    categoryKey: "選択",
  }),
  course({
    id: "demo-015",
    name: "ゼミナールI",
    teacher: "佐藤 一郎",
    faculty: "経済学部",
    department: "経済学科",
    credits: 4,
    targetYears: [3],
    semester: "通年",
    day: "金",
    period: 3,
    room: "ゼミ室1",
    overview: "少人数制で経済学のテーマを選び、文献講読と研究発表を行う。",
    evaluation: [{ type: "平常点", percentage: 60 }, { type: "レポート", percentage: 40 }],
    keywords: ["ゼミ", "演習", "卒業論文"],
    categoryKey: "必修",
  }),
  course({
    id: "demo-016",
    name: "英語コミュニケーションI",
    teacher: "Smith John",
    faculty: "経済学部",
    department: "経済学科",
    credits: 1,
    targetYears: [1],
    semester: "前期",
    day: "火",
    period: 1,
    room: "401",
    overview: "実践的な英語コミュニケーション能力の向上を目指す少人数授業。",
    evaluation: [{ type: "出席", percentage: 40 }, { type: "小テスト", percentage: 30 }, { type: "レポート", percentage: 30 }],
    keywords: ["英語", "語学"],
    categoryKey: "選択必修",
    categoryGroup: "教養選択必修",
  }),
  course({
    id: "demo-017",
    name: "情報処理演習",
    teacher: "木村 学",
    faculty: "経済学部",
    department: "経済学科",
    credits: 1,
    targetYears: [1],
    semester: "前期",
    day: "水",
    period: 1,
    room: "PC教室2",
    overview: "表計算ソフト・文書作成ソフトの基本操作とデータ処理の基礎を演習形式で学ぶ。",
    evaluation: [{ type: "小テスト", percentage: 50 }, { type: "出席", percentage: 50 }],
    keywords: ["情報処理", "Excel", "情報リテラシー"],
    categoryKey: "選択必修",
    categoryGroup: "教養選択必修",
  }),
  course({
    id: "demo-018",
    name: "哲学",
    teacher: "森田 修",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [1, 2],
    semester: "後期",
    day: "木",
    period: 1,
    room: "202",
    overview: "西洋哲学の主要な思想潮流を概観し、現代社会の諸問題を哲学的に考察する。",
    evaluation: [{ type: "レポート", percentage: 100 }],
    keywords: ["哲学", "思想"],
    categoryKey: "自由選択",
  }),
  course({
    id: "demo-019",
    name: "スポーツ実技",
    teacher: "体育 太郎",
    faculty: "経済学部",
    department: "経済学科",
    credits: 1,
    targetYears: [1, 2],
    semester: "前期",
    day: "金",
    period: 4,
    room: "体育館",
    overview: "生涯スポーツの視点から、実技を通じて健康・体力づくりの意義を学ぶ。",
    evaluation: [{ type: "出席", percentage: 70 }, { type: "平常点", percentage: 30 }],
    keywords: ["スポーツ", "体育"],
    categoryKey: "自由選択",
  }),
  course({
    id: "demo-020",
    name: "マーケティング論",
    teacher: "山田 恵",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [2, 3],
    semester: "前期",
    day: "木",
    period: 2,
    room: "303",
    overview: "市場調査、製品戦略、価格戦略、プロモーション戦略などマーケティングの基礎理論を学ぶ。",
    evaluation: [{ type: "試験", percentage: 40 }, { type: "レポート", percentage: 40 }, { type: "出席", percentage: 20 }],
    keywords: ["マーケティング", "市場調査"],
    categoryKey: "選択",
  }),
  course({
    id: "demo-021",
    name: "産業組織論",
    teacher: "西田 誠",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [3, 4],
    semester: "後期",
    day: "水",
    period: 2,
    room: "306",
    overview: "企業行動・市場構造・競争政策をゲーム理論等のミクロ経済学の手法を用いて分析する。",
    evaluation: [{ type: "試験", percentage: 80 }, { type: "出席", percentage: 20 }],
    keywords: ["産業組織", "ゲーム理論", "競争政策"],
    categoryKey: "選択",
    offeredYears: [2027],
  }),
  course({
    id: "demo-022",
    name: "環境経済学",
    teacher: "青木 恵子",
    faculty: "経済学部",
    department: "経済学科",
    credits: 2,
    targetYears: [3, 4],
    semester: "前期",
    day: "火",
    period: 3,
    room: "304",
    overview: "環境問題を経済学の視点から分析し、環境政策の設計・評価手法を学ぶ。",
    evaluation: [{ type: "レポート", percentage: 70 }, { type: "出席", percentage: 30 }],
    keywords: ["環境経済学", "環境政策", "持続可能性"],
    categoryKey: "自由選択",
  }),
];

export function nextCourseId(): string {
  return `demo-${Math.random().toString(36).slice(2, 10)}`;
}
